# Generated by Django 6.0.7 on 2026-08-11 22:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('policy_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('expired', 'Vencido'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('contract_period', models.CharField(choices=[('semiannual', 'Semestral'), ('annual', 'Anual')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='pets.pet')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('pet',), name='unique_active_policy_per_pet')],
            },
        ),
    ]
