# Generated by Django 6.0.7 on 2026-08-11 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato')], max_length=3)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Macho'), ('female', 'Hembra')], max_length=6)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('is_companion_animal', models.BooleanField(default=False)),
                ('photo_url', models.URLField(blank=True)),
                ('declared_age_months', models.PositiveIntegerField(help_text='Edad aproximada de la mascota en meses.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
