# Generated by Django 6.0.7 on 2026-08-14 21:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=150)),
                ('species', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato')], max_length=3)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('recommended', models.BooleanField(default=False)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'species'), name='unique_plan_name_per_species'), models.CheckConstraint(condition=models.Q(('monthly_price__gt', 0)), name='plan_monthly_price_positive')],
            },
        ),
    ]
